# Parsing XML document

trigger:
 - Master 

pool:
  name: Default

steps:  
  - task: PowerShell@2
    displayName: Iterating and storing XML attributes 
    inputs:
      targetType: inline
      script: |
        $XMLfile = "$(Build.SourcesDirectory)\WPF_Utilities.xml"
        $XMLNodes = [xml](Get-Content $XMLfile)
        foreach( $Utility in $XMLNodes.Build.Utilities.Utility )
        {
          if ( $Utility.SourceType -eq 'SVN' ) 
          { 
            $SVNSolutionfile = $Utility.Solutionfile 
            $SVNOutput = $Utility.Output
            $SVNFolder = $Utility.Folders.Folder
          }
          else
          {
            $GitSolutionfile = $Utility.Solutionfile
            $GitOutput = $Utility.Output
            $GitFolder = $Utility.Folders.Folder
          }
        }
        Write-Host "SVNSolutionfile: " $SVNSolutionfile
        Write-Host "SVN Output: " $SVNOutput
        Write-Host "SVNFolder: " $SVNFolder
        Write-Host "`n"
        Write-Host "GitSolutionfile: " $GitSolutionfile
        Write-Host "Git Output: " $GitOutput
        Write-Host "Git Folder: " $GitFolder
  
  - task: PowerShell@2
    displayName: Replace an attribute of XML
    inputs:
      targetType: inline
      script: |
        $XMLFilePath = "D:\Git\Hollo-World-Repo\ReplaceAssignment.XML"
        $XMLContent = [System.IO.File]::ReadAllText($XMLFilePath)-Replace( '(?<=_)\d{4}(?<!.sln)', "2023" )
        [System.IO.File]::WriteAllText($XMLFilePath, $XMLContent)

  - task: PowerShell@2
    displayName: Replace an attribute of XML
    inputs:
      targetType: inline
      script: |
        $XMLFilePath = "D:\Git\Hollo-World-Repo\ReplaceAssignment.XML"
        $XMLContent = [System.IO.File]::ReadAllText($XMLFilePath)-Replace('\W[P][A-T]{3}\W', "D:\Work\SVN")
        [System.IO.File]::WriteAllText($XMLFilePath, $XMLContent)

  - task: PowerShell@2
    displayName: Replace an attribute of an XML 
    inputs:
      targetType: inline
      script: |
        $XMLFilePath = "D:\Git\Hollo-World-Repo\ReplaceAssignment.XML"
        $XMLContent = [System.IO.File]::ReadAllText($XMLFilePath)-Replace('[e][a-z]-[A-Z]{2}', "INR")
        [System.IO.File]::WriteAllText($XMLFilePath, $XMLContent)
  
  - task: PowerShell@2
    displayName: INI file operation
    inputs:
      targetType: inline
      script: |
        $INIdata = Get-Content "D:\Git\Hollo-World-Repo\FBVariables.ini"
        $INIVariable = $INIdata[1]-split("=")
        $INIVersion= $INIVariable[1]-split("\.")
        $firstValue = $INIVersion[0]
        $secondValue = $INIVersion[1]
        $thirdValue = $INIVersion[2]
        $forthValue = $INIVersion[3]
        Write-Host "firstValue: "$firstValue
        Write-Host "secondValue: $secondValue
        Write-Host "thirdValue: "$thirdValue
        Write-Host "forthValue: "$forthValue