# C# console application

trigger:
 - Master 

pool:
  name: Default
  
variables: 
 buildConfiguration: 'Release'

steps:  
  - task: PowerShell@2
    displayName: parsing XML document
    inputs:
      targetType: inline
      script: |
        $XMLfile = "$(Build.SourcesDirectory)\WPF_Utilities.xml"
        $XMLData = [xml](Get-Content $XMLfile)
        $XMLData.Build.Utilities.Utility
        
  - task: 'DotNetCoreCLI@2'
    displayName: build $(buildConfiguration)
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: 'DotNetCoreCLI@2'
    displayName: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: 'PublishBuildArtifacts@1'
    displayName: publish artifact