# C# console application

trigger:
 - Master 

pool:
  name: Default
  
variables: 
 buildConfiguration: 'Release'

steps:  
  - task: PowerShell@2
    displayName: Iterating and storing XML attributes 
    inputs:
      targetType: inline
      script: |
        $XMLfile = "$(Build.SourcesDirectory)\WPF_Utilities.xml"
        $XMLNodes = [xml](Get-Content $XMLfile)
        foreach( $Utility in $XMLNodes.Build.Utilities.Utility )
        {
          if ( $Utility.SourceType -eq 'SVN' ) 
          { 
            $SVNSolutionfile = $Utility.Solutionfile 
            $SVNOutput = $Utility.Output
            $SVNFolder = $Utility.Folders.Folder
          }
          else
          {
            $GitSolutionfile = $Utility.Solutionfile
            $GitOutput = $Utility.Output
            $GitFolder = $Utility.Folders.Folder
          }
        }
        Write-Host "SVNSolutionfile: " $SVNSolutionfile
        Write-Host "SVN Output: " $SVNOutput
        Write-Host "SVNFolder: " $SVNFolder
        Write-Host "`n"
        Write-Host "GitSolutionfile: " $GitSolutionfile
        Write-Host "Git Output: " $GitOutput
        Write-Host "Git Folder: " $GitFolder
  
  - task: PowerShell@2
    displayName: Replace an attribute of XML
    inputs:
      targetType: inline
      script: |
        $XMLFilePath = "$(Build.SourcesDirectory)\ReplaceAssignment.xml"
        $XMLContent = [System.IO.File]::ReadAllText($XMLFilePath).Replace( "_2023", "_2010" )
        Write-Host $XMLContent
        [System.IO.File]::WriteAllText($XMLFilePath, $XMLContent)

  - task: 'DotNetCoreCLI@2'
    displayName: build $(buildConfiguration)
    inputs:
      command: build
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration)'
  
  - task: 'DotNetCoreCLI@2'
    displayName: dotnet publish --configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)
    inputs:
      command: publish
      publishWebProjects: false
      projects: '**/*.csproj'
      arguments: '--configuration $(buildConfiguration) --output $(Build.ArtifactStagingDirectory)'
      zipAfterPublish: true

  - task: 'PublishBuildArtifacts@1'
    displayName: publish artifact